name: stHorses
version: 2.1.2-SNAPSHOT
description: Horse storing plugin for the Spigot API
author: tmad40blue
website: http://tmad40.blue/

main: blue.tmad40.sthorses.Main
        
permissions:
    stHorses.*:
        description: Gives access to all plugin functions
        children:
            stHorses.save: true
            stHorses.store: true
    stHorses.place:
        description: Allows saving horses to saddles
        default: true
    stHorses.store:
        description: Allows spawning horses from saddles
        default: true